project_id = "avbswnnywjyvqfxezgfl"

[functions.ingest_event]
verify_jwt = false

[functions.send_telegram]
verify_jwt = false

[functions.media-cleanup]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.simulate-demo]
verify_jwt = true

[functions.demo-router]
verify_jwt = false

[functions.seed-demo-sources]
verify_jwt = false

[functions.billing-meter]
verify_jwt = false

[functions.billing-invoice]
verify_jwt = false

[functions.device-link]
verify_jwt = false

[functions.org-create]
verify_jwt = false

[functions.camera-add]
verify_jwt = false

[functions.stream-start]
verify_jwt = false

[functions.stream-stop]
verify_jwt = false

[functions.apikey-rotate]
verify_jwt = true

[functions.usage-summary]
verify_jwt = true

[functions.operational-quality]
verify_jwt = true

[functions.daily-report-generator]
verify_jwt = true

[functions.stream-tester]
verify_jwt = false

[functions.rtsp-to-hls]
verify_jwt = false
