version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: eagle-mediamtx
    restart: unless-stopped
    ports:
      # RTSP
      - "8554:8554"
      # HLS
      - "8888:8888"
      # WebRTC
      - "8889:8889"
      # API
      - "9997:9997"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - mediamtx_recordings:/recordings
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_LOGLEVEL=info
    networks:
      - eagle-network

  # Nginx para servir HLS e fazer proxy
  nginx-hls:
    image: nginx:alpine
    container_name: eagle-nginx-hls
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-hls.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mediamtx
    networks:
      - eagle-network

volumes:
  mediamtx_recordings:
    driver: local

networks:
  eagle-network:
    driver: bridge