global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: fusion
    static_configs:
      - targets: ["fusion:8080"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: frame_puller
    static_configs:
      - targets: ["frame-puller:9100"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: analytics
    static_configs:
      - targets: ["analytics:8090"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: multi_tracker
    static_configs:
      - targets: ["multi-tracker:8087"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: lpr_service
    static_configs:
      - targets: ["lpr-service:18070"]
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: clip_exporter
    static_configs:
      - targets: ["clip-exporter:8095"]
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: media_cleaner
    static_configs:
      - targets: ["media-cleaner:8097"]
    metrics_path: /metrics
    scrape_interval: 60s

  # AI Workers
  - job_name: peoplevision
    static_configs:
      - targets: ["peoplevision:8081"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: vehiclevision
    static_configs:
      - targets: ["vehiclevision:8082"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: safetyvision
    static_configs:
      - targets: ["safetyvision:8083"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: edubehavior
    static_configs:
      - targets: ["edubehavior:8084"]
    metrics_path: /metrics
    scrape_interval: 5s

  # Infrastructure monitoring
  - job_name: node_exporter
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s

  # GPU monitoring (cloud-only, will be DOWN locally)
  - job_name: dcgm_gpu
    static_configs:
      - targets: ["dcgm-exporter:9400"]
    scrape_interval: 10s

  # Backup monitoring
  - job_name: backup_exporter
    static_configs:
      - targets: ["backup:8098"]
    metrics_path: /metrics
    scrape_interval: 60s