global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: fusion
    static_configs:
      - targets: ["fusion:8080"]
    metrics_path: /metrics

  - job_name: frame_puller
    static_configs:
      - targets: ["frame-puller:9100"]
    metrics_path: /metrics

  - job_name: analytics
    static_configs:
      - targets: ["analytics:8090"]
    metrics_path: /metrics

  - job_name: multi_tracker
    static_configs:
      - targets: ["multi-tracker:8087"]
    metrics_path: /metrics

  - job_name: lpr_service
    static_configs:
      - targets: ["lpr-service:18070"]
    metrics_path: /metrics

  - job_name: clip_exporter
    static_configs:
      - targets: ["clip-exporter:8095"]
    metrics_path: /metrics

  - job_name: media_cleaner
    static_configs:
      - targets: ["media-cleaner:8097"]
    metrics_path: /metrics

  # Cloud-only targets; will be DOWN locally
  - job_name: dcgm_gpu
    static_configs:
      - targets: ["dcgm-exporter:9400"]
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]