version: "3.9"

services:
  yolo-detection:
    build: .
    container_name: yolo-detection
    restart: unless-stopped
    ports:
      - "18060:18060"
    environment:
      - YOLO_MODEL=yolov8x.pt
    volumes:
      - ./models:/app/models  # Cache de modelos
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18060/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s