// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { loadPublicEnv } from '@/lib/publicEnv';

const runtime = loadPublicEnv();

if (!runtime.SUPABASE_URL || !runtime.SUPABASE_ANON_KEY) {
  throw new Error("Config ausente: defina SUPABASE_URL/ANON_KEY via window.__ENV ou <meta>.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  runtime.SUPABASE_URL as string,
  runtime.SUPABASE_ANON_KEY as string,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
